apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-data-handler-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-data-handler-service
  template:
    metadata:
      labels:
        app: device-data-handler-service
    spec:
      containers:
        - name: device-data-handler-service
          image: ihorzadyra/device-data-handler-service:0.0.3-SNAPSHOT
          ports:
            - containerPort: 9000
              protocol: TCP
          resources: {}
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600


---

apiVersion: v1
kind: Service
metadata:
  name: device-data-handler-service-node-port
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: device-data-handler-service
