addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"        % "0.10.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager"  % "1.8.1")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"        % "1.8.2")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.10.0-RC1")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"         % "2.5.2")
